name: Smart Kitchen CI

on:
  pull_request:
    branches:
      - v1.0

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Type Check
        run: npx tsc --noEmit

      - name: Build Application
        run: npm run build